---
# tasks file for docke

- name: Install docker
  package:
    name: docker.io
    state: present

- name: Add users to docker group
  user:
    user: "{{ item }}"
    append: true
    groups:
      - docker
  with_items: "{{ docker_users }}"
