---
# tasks file for docker

- name: Install docker
  package:
    name: docker.io
    state: present
  become: true

- name: Enable docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Add users to docker group
  user:
    user: "{{ item }}"
    append: true
    groups:
      - docker
  with_items: "{{ docker_users }}"
  become: true
